#!/bin/sh
license='
Converts IPADDRESS to CIDR, or returns CIDR if already a valid one
Copyright (C) 2018 z0noxz, <chris@noxz.tech>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
'

count_ones() {

    dec=$1
    base=2
    result=0

    while [ "$dec" -ne 0 ]; do
        if [ $((dec % base)) -eq 1 ]; then
            result=$((result+1))
        fi
        dec=$((dec / base))
    done

    printf '%d' "$result"
}

do_ip2cidr() {

    ip=$1
    OIFS=$IFS
    result=0
    i=0

    IFS=\.
    for item in $ip; do
        if [ "$item" -eq "$item" ] 2> /dev/null && \
            [ "$item" -le 256 ] && [ "$item" -ge 0 ]; then
            i=$((i+1))
            case $i in
                1)
                    result=$((result+item*16777216))
                    ;;
                2)
                    result=$((result+item*65536))
                    ;;
                3)
                    result=$((result+item*256))
                    ;;
                4)
                    result=$((result+item))
                    ;;
            esac
        else
            return 1
        fi
    done
    IFS=$OIFS

    printf '%d\n' "$(count_ones "$result")"
}

# check if input already is a CIDR, and if not process it
if [ "$1" -eq "$1" ] 2> /dev/null && [ "$1" -le 32 ] && [ "$1" -gt 0 ]; then
    printf '%d\n' "$1" && exit 0
else
    do_ip2cidr "$1" && exit 0
fi


# if all fails print usage
program_name="${0##*/}"
printf 'Usage: %s IPADDRESS

LICENSE NOTICE
%s
' "$program_name" "$license" >&2

exit 1
