#!/bin/sh
license='
Converts IPADDRESS to CIDR, or returns CIDR if already a valid one
Copyright (C) 2018 z0noxz, <chris@noxz.tech>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
'

count_ones() {

    # variable declaration
    dec=$1
    base=2
    result=0
    found_zero=-1

    # base convert decimal ip address to binary
    while [ "$dec" -ne 0 ]; do
        if [ $((dec % base)) -eq 1 ]; then
            # check if mask is invalid
            if [ "$found_zero" -eq 1 ]; then
                printf '%d' "-1"
                return 1
            fi

            # count one
            result=$((result+1))
            found_zero=0
        else
            # detect zero after a one
            if [ "$found_zero" -eq 0 ]; then
                found_zero=1
            fi
        fi
        dec=$((dec / base))
    done

    # return value
    printf '%d' "$result"
    return 0
}

do_ip2cidr() {

    # variable declaration
    ip=$1
    cidr=-1
    OIFS=$IFS
    result=0
    i=0

    # parse ip address
    IFS=\.
    for item in $ip; do
        if [ "$item" -eq "$item" ] 2> /dev/null && \
            [ "$item" -le 256 ] && [ "$item" -ge 0 ]; then
            i=$((i+1))
            case $i in
                1)
                    result=$((result+item*16777216))
                    ;;
                2)
                    result=$((result+item*65536))
                    ;;
                3)
                    result=$((result+item*256))
                    ;;
                4)
                    result=$((result+item))
                    ;;
            esac
        else
            return 1
        fi
    done
    IFS=$OIFS

    # check if ip address was valid, and if not fail
    if [ "$ip" = "" ] || [ "$i" -ne 4 ]; then
        return 1
    fi

    # calculate CIDR
    cidr=$(count_ones "$result")

    # check if CIDR is valid, and if not fail
    if [ "$cidr" -eq -1 ]; then
        return 1
    fi

    # print CIDR
    printf '%d\n' "$cidr"

    # success
    return 0
}

# check if input already is a CIDR, and if not process it
if [ "$1" -eq "$1" ] 2> /dev/null && [ "$1" -le 32 ] && [ "$1" -gt 0 ]; then
    printf '%d\n' "$1" && exit 0
else
    do_ip2cidr "$1" && exit 0
fi


# if all fails print usage
program_name="${0##*/}"
printf 'Usage: %s IPADDRESS

The IPADDRESS must be a valid subnet mask.

LICENSE NOTICE
%s
' "$program_name" "$license" >&2

exit 1
